apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  targetNamespace: karpenter
  interval: 5m
  chart:
    spec:
      chart: karpenter
      version: 0.19.2
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: karpenter
      interval: 10m
  values:
    replicas: 1
    serviceAccount:
      create: true
      name: "karpenter"
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::544965141528:role/demo-k8s-karpenter
    settings:
      aws:
        clusterName: "demo-k8s"
        clusterEndpoint: "https://301FC38C993FCE11660A3BECE9FA4250.yl4.eu-central-1.eks.amazonaws.com"
        defaultInstanceProfile: "KarpenterNodeInstanceProfile-demo-k8s"
    logLevel: info
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace